/**
 * @file blender_generator.cpp
 * @brief Blender Geometry Nodes Python code generator
 */

#include "blender_generator.h"
#include <cmath>
#include <algorithm>

namespace scad2blender {

std::string BlenderGenerator::generate(ASTNodePtr root) {
    code_.str("");
    code_.clear();
    indent_ = 0;
    node_counter_ = 0;
    last_output_ = "";
    defined_modules_.clear();
    variables_.clear();
    group_input_vars_.clear();
    top_level_vars_.clear();
    in_module_ = false;
    module_uses_children_ = false;

    emitHeader();
    emitHelperFunctions();

    // First pass: collect modules and variables
    for (auto& child : root->children()) {
        if (child->type() == ASTNode::Type::Module) {
            auto* mod = dynamic_cast<ModuleNode*>(child.get());
            if (mod) {
                defined_modules_.insert(mod->name());
            }
        } else if (child->type() == ASTNode::Type::Assignment) {
            auto* assign = dynamic_cast<AssignmentNode*>(child.get());
            if (assign) {
                variables_[assign->name()] = assign->value();
                top_level_vars_.insert(assign->name());
            }
        }
    }

    emitVariables();

    // Pre-scan all modules to collect variables that will become group_input sockets
    // This must happen before emitting module functions so resolveExprTree knows
    // which variables should be group_input leaf nodes
    for (auto& child : root->children()) {
        if (child->type() == ASTNode::Type::Module) {
            auto* mod = dynamic_cast<ModuleNode*>(child.get());
            if (mod) {
                collectGroupInputVars(*mod);
            }
        }
    }

    // Also register top-level variables as group_input vars (they get sockets in build_geometry)
    for (const auto& [name, value] : variables_) {
        if (value.isNumber() || value.isBool() || value.isString() ||
            (value.isVector() && value.size() == 3)) {
            group_input_vars_.insert(name);
        }
    }

    // Emit module functions
    for (auto& child : root->children()) {
        if (child->type() == ASTNode::Type::Module) {
            auto* mod = dynamic_cast<ModuleNode*>(child.get());
            if (mod) {
                emitModuleFunction(*mod);
            }
        }
    }

    // Emit main build_geometry function
    auto* rootNode = dynamic_cast<RootNode*>(root.get());
    if (rootNode) {
        emitBuildGeometry(*rootNode);
    }

    emitFooter();

    return code_.str();
}

void BlenderGenerator::emit(const std::string& line) {
    code_ << indent() << line << "\n";
}

void BlenderGenerator::emitBlank() {
    code_ << "\n";
}

std::string BlenderGenerator::indent() const {
    return std::string(indent_ * 4, ' ');
}

std::string BlenderGenerator::newNodeId() {
    return "node_" + std::to_string(node_counter_++);
}

void BlenderGenerator::emitHeader() {
    emit("\"\"\"");
    emit("Blender Geometry Nodes script generated from OpenSCAD");
    emit("Generated by scad2blender");
    emit("\"\"\"");
    emitBlank();
    emit("import bpy");
    emit("import math");
    emit("import sys");
    emit("import os");
    emit("from mathutils import Vector, Matrix");
    emitBlank();
}

void BlenderGenerator::emitHelperFunctions() {
    emit("def create_geometry_nodes_modifier(obj, name='GeometryNodes'):");
    indent_++;
    emit("\"\"\"Create and setup geometry nodes modifier\"\"\"");
    emit("modifier = obj.modifiers.new(name=name, type='NODES')");
    emit("node_group = bpy.data.node_groups.new(name=name, type='GeometryNodeTree')");
    emit("modifier.node_group = node_group");
    emit("return node_group, modifier");
    indent_--;
    emitBlank();

    emit("def add_input_socket(node_group, name, socket_type, default_value=None):");
    indent_++;
    emit("\"\"\"Add an input socket to the node group\"\"\"");
    emit("socket = node_group.interface.new_socket(name=name, in_out='INPUT', socket_type=socket_type)");
    emit("if default_value is not None and hasattr(socket, 'default_value'):");
    indent_++;
    emit("socket.default_value = default_value");
    indent_--;
    emit("return socket");
    indent_--;
    emitBlank();

    emit("def setup_node_tree(node_group):");
    indent_++;
    emit("\"\"\"Setup input/output nodes\"\"\"");
    emit("nodes = node_group.nodes");
    emit("links = node_group.links");
    emit("nodes.clear()");
    emitBlank();
    emit("group_input = nodes.new('NodeGroupInput')");
    emit("group_input.location = (-400, 0)");
    emitBlank();
    emit("group_output = nodes.new('NodeGroupOutput')");
    emit("group_output.location = (400, 0)");
    emitBlank();
    emit("# Add Geometry socket to output");
    emit("node_group.interface.new_socket(name='Geometry', in_out='OUTPUT', socket_type='NodeSocketGeometry')");
    emitBlank();
    emit("return nodes, links, group_input, group_output");
    indent_--;
    emitBlank();

    emit("def link_nodes(links, from_node, from_socket, to_node, to_socket):");
    indent_++;
    emit("\"\"\"Create a link between two node sockets\"\"\"");
    emit("if from_node is None or to_node is None:");
    indent_++;
    emit("return");
    indent_--;
    emit("# Try the specified socket name, fall back to alternatives");
    emit("try:");
    indent_++;
    emit("out_socket = from_node.outputs.get(from_socket)");
    emit("if out_socket is None:");
    indent_++;
    emit("# Try common alternatives");
    emit("for alt in ['Mesh', 'Geometry', 'Curve']:");
    indent_++;
    emit("out_socket = from_node.outputs.get(alt)");
    emit("if out_socket is not None:");
    indent_++;
    emit("break");
    indent_--;
    indent_--;
    indent_--;
    emit("if out_socket is None and len(from_node.outputs) > 0:");
    indent_++;
    emit("out_socket = from_node.outputs[0]  # Use first output as fallback");
    indent_--;
    emit("if out_socket is not None:");
    indent_++;
    emit("links.new(out_socket, to_node.inputs[to_socket])");
    indent_--;
    indent_--;
    emit("except Exception as e:");
    indent_++;
    emit("print(f'Link error: {e}')");
    indent_--;
    indent_--;
    emitBlank();
}

void BlenderGenerator::emitVariables() {
    // Variables are now added as node group inputs in build_geometry
    // This function is kept for compatibility but doesn't emit global Python variables
}

bool BlenderGenerator::isSimpleVariableRef(const Value& value) {
    // Check if this is a simple variable reference (just a name, no operators)
    // that corresponds to a group_input socket
    if (!value.isExpression()) return false;
    const std::string& expr = value.toString();
    // If it contains operators or parentheses, it's a computed expression
    if (expr.find('+') != std::string::npos ||
        expr.find('-') != std::string::npos ||
        expr.find('*') != std::string::npos ||
        expr.find('/') != std::string::npos ||
        expr.find('(') != std::string::npos ||
        expr.find(' ') != std::string::npos) {
        return false;
    }
    // Only treat as a linkable variable ref if it has a group_input socket
    if (group_input_vars_.find(expr) == group_input_vars_.end()) {
        return false;
    }
    return true;
}

bool BlenderGenerator::exprTreeHasOnlyGroupInputVars(const ExprNodePtr& tree) {
    if (!tree) return true;
    switch (tree->kind) {
        case ExprNode::Kind::Literal:
            return true;
        case ExprNode::Kind::VarRef:
            return group_input_vars_.find(tree->var_name) != group_input_vars_.end();
        case ExprNode::Kind::UnaryOp:
            return exprTreeHasOnlyGroupInputVars(tree->left);
        case ExprNode::Kind::BinaryOp:
            return exprTreeHasOnlyGroupInputVars(tree->left) &&
                   exprTreeHasOnlyGroupInputVars(tree->right);
    }
    return true;
}

void BlenderGenerator::emitSetInputOrLink(const std::string& nodeId, const std::string& inputName,
                                          const Value& value, const std::string& pythonValue) {
    // Try expression tree path first
    ExprNodePtr tree = resolveExprTree(value);
    if (tree && tree->hasVariableRefs()) {
        // Only use the node-tree path if all variable refs are group_input sockets.
        // Module parameters (local Python variables) can't be linked as Blender nodes.
        if (exprTreeHasOnlyGroupInputVars(tree)) {
            auto result = emitExpressionNodeTree(tree);
            connectExprResultNamed(result, nodeId, inputName);
            return;
        }
        // Fall through to use pythonValue (evaluated at compile time)
    }

    if (isSimpleVariableRef(value)) {
        // Link from group_input for simple variable references
        std::string varName = value.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);  // Remove $ prefix for socket name
        }
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['" + inputName + "'])");
    } else {
        // For computed expressions or literal values, use default_value
        emit(nodeId + ".inputs['" + inputName + "'].default_value = " + pythonValue);
    }
}

void BlenderGenerator::emitModuleFunction(ModuleNode& node) {
    in_module_ = true;
    module_uses_children_ = moduleUsesChildren(node);

    // Build function signature with parameters
    std::string params = "nodes, links, group_input, x_pos, y_pos";
    for (const auto& param : node.parameters()) {
        params += ", " + param + "=None";
    }
    params += ", children_geo=None";

    emit("def module_" + node.name() + "(" + params + "):");
    indent_++;
    emit("\"\"\"OpenSCAD module: " + node.name() + "\"\"\"");
    emit("start_y = y_pos");
    emit("last_geo = children_geo");
    emitBlank();

    // Process module body
    for (auto& child : node.children()) {
        if (!child->isDisabled() && !child->isBackground()) {
            child->accept(*this);
        }
    }

    emitBlank();
    emit("return last_geo, y_pos");
    indent_--;
    emitBlank();

    in_module_ = false;
    module_uses_children_ = false;
}

void BlenderGenerator::emitBuildGeometry(RootNode& node) {
    emit("def build_geometry(node_group):");
    indent_++;
    emit("\"\"\"Build the geometry nodes graph\"\"\"");
    emitBlank();

    // Add input sockets for all top-level SCAD variables BEFORE setting up node tree
    // This ensures group_input node will have the outputs available
    if (!variables_.empty()) {
        emit("# Add input sockets for OpenSCAD variables");
        for (const auto& [name, value] : variables_) {
            // Only process top-level variables, not module-internal ones
            if (top_level_vars_.find(name) == top_level_vars_.end()) continue;

            std::string socketName = name;
            if (name[0] == '$') {
                socketName = name.substr(1);  // Remove $ prefix
            }

            // Track this as a group_input variable
            group_input_vars_.insert(name);

            // Determine socket type based on value type
            if (value.isBool()) {
                emit("add_input_socket(node_group, '" + socketName + "', 'NodeSocketBool', " + value.toPython() + ")");
            } else if (value.isNumber()) {
                emit("add_input_socket(node_group, '" + socketName + "', 'NodeSocketFloat', " + value.toPython() + ")");
            } else if (value.isString()) {
                emit("add_input_socket(node_group, '" + socketName + "', 'NodeSocketString', " + value.toPython() + ")");
            } else if (value.isVector()) {
                if (value.size() == 3) {
                    // Evaluate each component numerically to avoid expression references
                    std::string vecDefault = "(";
                    for (size_t i = 0; i < 3; ++i) {
                        if (i > 0) vecDefault += ", ";
                        vecDefault += std::to_string(value[i].toNumber());
                    }
                    vecDefault += ")";
                    emit("add_input_socket(node_group, '" + socketName + "', 'NodeSocketVector', " + vecDefault + ")");
                } else {
                    // For other vector sizes, use float for now
                    emit("# Vector " + socketName + " has non-standard size, skipping");
                }
            } else {
                emit("# Unsupported type for variable: " + socketName);
            }
        }
        emitBlank();
    }

    // Now setup the node tree - group_input will have the socket outputs
    emit("nodes, links, group_input, group_output = setup_node_tree(node_group)");
    emitBlank();

    // Emit Python variable assignments for group_input parameters
    // so that Python-level code (e.g. polyhedron vertex lists) can reference them
    if (!variables_.empty()) {
        emit("# Python variables for group_input parameters");
        for (const auto& [name, value] : variables_) {
            // Only process top-level variables, not module-internal ones
            if (top_level_vars_.find(name) == top_level_vars_.end()) continue;

            std::string varName = name;
            if (name[0] == '$') {
                varName = name.substr(1);
            }
            // Only emit for types that got add_input_socket calls
            if (value.isNumber() || value.isBool() || value.isString()) {
                emit(varName + " = " + value.toPython());
            } else if (value.isVector() && value.size() == 3) {
                // Evaluate each component numerically to avoid expression references
                std::string vecVal = "(";
                for (size_t i = 0; i < 3; ++i) {
                    if (i > 0) vecVal += ", ";
                    vecVal += std::to_string(value[i].toNumber());
                }
                vecVal += ")";
                emit(varName + " = " + vecVal);
            }
        }
        emitBlank();
    }

    emit("x_pos = 0");
    emit("y_pos = 0");
    emit("last_geo = None");
    emit("all_geometry = []  # Collect all top-level geometry");
    emitBlank();

    // Process top-level statements (excluding modules and assignments)
    // Collect geometry from each statement
    for (auto& child : node.children()) {
        if (child->type() != ASTNode::Type::Module &&
            child->type() != ASTNode::Type::Assignment &&
            !child->isDisabled() && !child->isBackground()) {
            emit("# --- Top-level statement ---");
            emit("last_geo = None");
            child->accept(*this);
            emit("if last_geo is not None:");
            indent_++;
            emit("all_geometry.append(last_geo)");
            indent_--;
            emitBlank();
        }
    }

    emitBlank();
    emit("# Join all top-level geometry");
    emit("if len(all_geometry) == 0:");
    indent_++;
    emit("pass  # No geometry to output");
    indent_--;
    emit("elif len(all_geometry) == 1:");
    indent_++;
    emit("link_nodes(links, all_geometry[0], 'Geometry', group_output, 'Geometry')");
    indent_--;
    emit("else:");
    indent_++;
    emit("join_node = nodes.new('GeometryNodeJoinGeometry')");
    emit("join_node.location = (x_pos, y_pos)");
    emit("for geo in all_geometry:");
    indent_++;
    emit("link_nodes(links, geo, 'Geometry', join_node, 'Geometry')");
    indent_--;
    emit("link_nodes(links, join_node, 'Geometry', group_output, 'Geometry')");
    indent_--;
    indent_--;
    emitBlank();
}

void BlenderGenerator::emitFooter() {
    emit("def main():");
    indent_++;
    emit("\"\"\"Main entry point\"\"\"");
    emit("# Create mesh object");
    emit("mesh = bpy.data.meshes.new('OpenSCAD_Mesh')");
    emit("obj = bpy.data.objects.new('OpenSCAD_Object', mesh)");
    emit("bpy.context.collection.objects.link(obj)");
    emitBlank();
    emit("# Create geometry nodes");
    emit("node_group, modifier = create_geometry_nodes_modifier(obj)");
    emit("build_geometry(node_group)");
    emitBlank();
    emit("# Set modifier input values from socket defaults");
    emit("for item in node_group.interface.items_tree:");
    indent_++;
    emit("if hasattr(item, 'item_type') and item.item_type == 'SOCKET' and item.in_out == 'INPUT':");
    indent_++;
    emit("if hasattr(item, 'default_value') and hasattr(item, 'identifier'):");
    indent_++;
    emit("try:");
    indent_++;
    emit("modifier[item.identifier] = item.default_value");
    indent_--;
    emit("except Exception:");
    indent_++;
    emit("pass");
    indent_--;
    indent_--;
    indent_--;
    indent_--;
    emitBlank();
    emit("# Select the object");
    emit("bpy.context.view_layer.objects.active = obj");
    emit("obj.select_set(True)");
    emitBlank();
    emit("# Evaluate the geometry nodes modifier to produce mesh");
    emit("depsgraph = bpy.context.evaluated_depsgraph_get()");
    emit("eval_obj = obj.evaluated_get(depsgraph)");
    emit("eval_mesh = eval_obj.to_mesh()");
    emitBlank();
    emit("# Copy evaluated mesh back so the object has real geometry for export");
    emit("obj.data = bpy.data.meshes.new_from_object(eval_obj)");
    emit("eval_obj.to_mesh_clear()");
    emitBlank();
    emit("# Remove the modifier so the exporter uses the baked mesh");
    emit("obj.modifiers.clear()");
    emitBlank();
    emit("# Remove helper objects (polyhedron sources, etc.)");
    emit("for o in list(bpy.data.objects):");
    indent_++;
    emit("if o != obj and o.name.endswith('_polyhedron'):");
    indent_++;
    emit("bpy.data.objects.remove(o, do_unlink=True)");
    indent_--;
    indent_--;
    emitBlank();
    emit("# Determine STL output path from script filename");
    emit("script_path = os.path.abspath(__file__)");
    emit("stl_path = os.path.splitext(script_path)[0] + '.stl'");
    emitBlank();
    emit("# Export to STL");
    emit("bpy.ops.object.select_all(action='DESELECT')");
    emit("obj.select_set(True)");
    emit("try:");
    indent_++;
    emit("bpy.ops.wm.stl_export(filepath=stl_path, export_selected_objects=True)");
    indent_--;
    emit("except AttributeError:");
    indent_++;
    emit("bpy.ops.export_mesh.stl(filepath=stl_path, use_selection=True)");
    indent_--;
    emit("print(f'Exported STL to: {stl_path}')");
    indent_--;
    emitBlank();
    emit("if __name__ == '__main__':");
    indent_++;
    emit("main()");
    indent_--;
}

// Visitor implementations
void BlenderGenerator::visit(RootNode& node) {
    // Root is handled by emitBuildGeometry
}

void BlenderGenerator::visit(PrimitiveNode& node) {
    switch (node.type()) {
        case ASTNode::Type::Cube:
            emitCube(node.args());
            break;
        case ASTNode::Type::Sphere:
            emitSphere(node.args());
            break;
        case ASTNode::Type::Cylinder:
            emitCylinder(node.args());
            break;
        case ASTNode::Type::Circle:
            emitCircle(node.args());
            break;
        case ASTNode::Type::Square:
            emitSquare(node.args());
            break;
        case ASTNode::Type::Polyhedron:
            emitPolyhedron(node.args());
            break;
        case ASTNode::Type::Text:
            emitText(node.args());
            break;
        default:
            emit("# Unsupported primitive type");
            break;
    }
}

void BlenderGenerator::visit(TransformNode& node) {
    switch (node.type()) {
        case ASTNode::Type::Translate:
            processChildren(node);
            emitTranslate(node.args());
            break;
        case ASTNode::Type::Rotate:
            processChildren(node);
            emitRotate(node.args());
            break;
        case ASTNode::Type::Scale:
            processChildren(node);
            emitScale(node.args());
            break;
        case ASTNode::Type::Mirror:
            processChildren(node);
            emitMirror(node.args());
            break;
        case ASTNode::Type::Color:
            // Color is not directly supported in Geometry Nodes,
            // just process children and pass geometry through
            emit("# Color transform (visual only, not applied in Geometry Nodes)");
            processChildren(node);
            break;
        case ASTNode::Type::Offset:
            processChildren(node);
            emitOffset(node.args());
            break;
        case ASTNode::Type::Hull:
            processChildren(node);
            emitHull(node.args());
            break;
        case ASTNode::Type::Minkowski:
            processChildren(node);
            emitMinkowski(node.args());
            break;
        default:
            emit("# Unsupported transform type");
            processChildren(node);
            break;
    }
}

void BlenderGenerator::visit(BooleanNode& node) {
    emitBooleanOp(node);
}

void BlenderGenerator::visit(ExtrudeNode& node) {
    processChildren(node);

    switch (node.type()) {
        case ASTNode::Type::LinearExtrude:
            emitLinearExtrude(node.args());
            break;
        case ASTNode::Type::RotateExtrude:
            emitRotateExtrude(node.args());
            break;
        default:
            emit("# Unsupported extrude type");
            break;
    }
}

void BlenderGenerator::visit(ModuleNode& node) {
    // Module definitions are handled separately
}

void BlenderGenerator::visit(ModuleCallNode& node) {
    if (defined_modules_.find(node.name()) != defined_modules_.end()) {
        // Call a user-defined module
        std::string nodeId = newNodeId();
        emit("# Call module: " + node.name());

        // If the module call has children (e.g. outline(wall=2) circle(15)),
        // process them first to produce geometry that becomes children_geo
        if (!node.children().empty()) {
            emit("# Process children geometry for " + node.name());
            std::string savedGeo = "saved_geo_" + std::to_string(node_counter_++);
            emit(savedGeo + " = last_geo");
            emit("last_geo = None");
            for (auto& child : node.children()) {
                if (!child->isDisabled() && !child->isBackground()) {
                    child->accept(*this);
                }
            }
            emit("children_geo_tmp = last_geo");
            emit("last_geo = " + savedGeo);
        }

        // Build argument list
        std::string argStr = "nodes, links, group_input, x_pos, y_pos";

        // Add named arguments from the call
        for (const auto& arg : node.args()) {
            if (arg.first[0] != '_') {  // Skip positional args for now
                argStr += ", " + arg.first + "=" + arg.second.toPython();
            }
        }

        if (!node.children().empty()) {
            argStr += ", children_geo=children_geo_tmp";
        } else {
            argStr += ", children_geo=last_geo";
        }

        emit(nodeId + ", y_pos = module_" + node.name() + "(" + argStr + ")");
        emit("last_geo = " + nodeId);
        emit("x_pos += 200");
    } else {
        emit("# Unknown module: " + node.name());
    }
}

void BlenderGenerator::visit(ForLoopNode& node) {
    const Value& range = node.range();

    if (range.isRange()) {
        emit("# For loop: " + node.variable());
        std::string loopVar = node.variable();
        emit("for " + loopVar + " in " + range.toPython() + ":");
        indent_++;

        for (auto& child : node.children()) {
            child->accept(*this);
        }

        indent_--;
    } else if (range.isVector()) {
        emit("# For loop over vector: " + node.variable());
        emit("for " + node.variable() + " in " + range.toPython() + ":");
        indent_++;

        for (auto& child : node.children()) {
            child->accept(*this);
        }

        indent_--;
    }
}

void BlenderGenerator::visit(IfElseNode& node) {
    emit("# Conditional");
    const Value& cond = node.condition();

    if (cond.isBool()) {
        if (cond.toBool()) {
            emit("# if (true):");
            for (auto& child : node.children()) {
                child->accept(*this);
            }
        } else if (node.elseBranch()) {
            emit("# if (false) - else branch:");
            node.elseBranch()->accept(*this);
        }
    } else {
        // Runtime condition - emit both branches
        emit("# Runtime conditional - emitting if branch");
        for (auto& child : node.children()) {
            child->accept(*this);
        }
    }
}

void BlenderGenerator::visit(AssignmentNode& node) {
    // Store variable in local scope
    variables_[node.name()] = node.value();
    // Emit Python variable assignment if inside module
    if (in_module_) {
        const Value& val = node.value();
        if (val.isExpression()) {
            // Resolve expression to numeric value to avoid referencing Python
            // variables that aren't in scope in module functions
            double numVal = evaluateExpr(val);
            emit(node.name() + " = " + std::to_string(numVal));
        } else if (val.isVector()) {
            // Evaluate vector components numerically to avoid expression references
            std::string vecStr = "(";
            for (size_t i = 0; i < val.size(); ++i) {
                if (i > 0) vecStr += ", ";
                if (val[i].isExpression()) {
                    vecStr += std::to_string(evaluateExpr(val[i]));
                } else {
                    vecStr += val[i].toPython();
                }
            }
            vecStr += ")";
            emit(node.name() + " = " + vecStr);
        } else {
            emit(node.name() + " = " + val.toPython());
        }
    }
}

void BlenderGenerator::visit(ChildrenNode& node) {
    if (in_module_) {
        emit("# children() - restore passed geometry");
        emit("last_geo = children_geo");
    }
}

// Primitive generators
void BlenderGenerator::emitCube(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value size = getArg(args, "size", getPositionalArg(args, 0, Value(1.0)));
    Value center = getArg(args, "center", Value(false));

    // Resolve variable references that aren't group_input sockets to their values
    if (size.isExpression() && !isSimpleVariableRef(size)) {
        auto it = variables_.find(size.toString());
        if (it != variables_.end() && !it->second.isExpression()) {
            size = it->second;
        }
    }

    emit("# Cube");
    emit(nodeId + " = nodes.new('GeometryNodeMeshCube')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    if (isSimpleVariableRef(size)) {
        // Link size from group_input - need to handle scalar vs vector
        std::string varName = size.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);
        }
        emit("# Size from variable: " + varName);
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Size'])");
    } else if (size.isVector() && size.size() >= 3 && vectorHasExprTrees(size)) {
        emitVectorWithExprTrees(nodeId, "Size", size);
    } else if (size.isVector() && size.size() >= 3) {
        emit(nodeId + ".inputs['Size'].default_value = " + vectorToPython(size));
    } else {
        // Scalar size — check for expression tree
        ExprNodePtr sizeTree = getOrMakeLiteralTree(size);
        if (sizeTree->hasVariableRefs()) {
            emitScalarToAllVectorComponents(nodeId, "Size", sizeTree);
        } else {
            double s = size.toNumber();
            emit(nodeId + ".inputs['Size'].default_value = (" +
                 std::to_string(s) + ", " + std::to_string(s) + ", " + std::to_string(s) + ")");
        }
    }

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");

    // Handle center=false (translate by half size)
    if (!center.toBool() && !isSimpleVariableRef(center)) {
        emitBlank();
        emit("# Translate for center=false");
        std::string transId = newNodeId();
        emit(transId + " = nodes.new('GeometryNodeTransform')");
        emit(transId + ".location = (x_pos, y_pos)");

        if (size.isVector() && size.size() >= 3) {
            // Vector size — check each component for expression trees
            bool hasExprs = false;
            ExprNodePtr compTrees[3];
            for (int i = 0; i < 3; ++i) {
                compTrees[i] = getOrMakeLiteralTree(size[i]);
                if (compTrees[i]->hasVariableRefs()) hasExprs = true;
            }

            if (hasExprs || vectorHasExprTrees(size)) {
                // Build size[i] / 2 expression trees
                std::string combineId = newNodeId();
                emit("# CombineXYZ for center=false Translation");
                emit(combineId + " = nodes.new('ShaderNodeCombineXYZ')");
                emit(combineId + ".location = (x_pos, y_pos)");
                emit("y_pos -= 50");

                const char* components[] = {"X", "Y", "Z"};
                for (int i = 0; i < 3; ++i) {
                    ExprNodePtr halfTree = ExprNode::makeBinary(
                        ExprNode::Op::DIVIDE, compTrees[i], ExprNode::makeLiteral(2.0));
                    auto result = emitExpressionNodeTree(halfTree);
                    connectExprResultNamed(result, combineId, components[i]);
                }

                emit("links.new(" + combineId + ".outputs['Vector'], " + transId + ".inputs['Translation'])");
            } else {
                emit(transId + ".inputs['Translation'].default_value = (" +
                     std::to_string(size[0].toNumber() / 2) + ", " +
                     std::to_string(size[1].toNumber() / 2) + ", " +
                     std::to_string(size[2].toNumber() / 2) + ")");
            }
        } else {
            // Scalar size — check for expression tree
            ExprNodePtr sizeTree = getOrMakeLiteralTree(size);
            if (sizeTree->hasVariableRefs()) {
                ExprNodePtr halfTree = ExprNode::makeBinary(
                    ExprNode::Op::DIVIDE, sizeTree, ExprNode::makeLiteral(2.0));
                emitScalarToAllVectorComponents(transId, "Translation", halfTree);
            } else {
                double s = size.toNumber() / 2;
                emit(transId + ".inputs['Translation'].default_value = (" +
                     std::to_string(s) + ", " + std::to_string(s) + ", " + std::to_string(s) + ")");
            }
        }

        emit("link_nodes(links, last_geo, 'Mesh', " + transId + ", 'Geometry')");
        emit("last_geo = " + transId);
        emit("x_pos += 200");
    }
}

void BlenderGenerator::emitSphere(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value r = getArg(args, "r", getPositionalArg(args, 0, Value(1.0)));
    Value d = getArg(args, "d", Value());
    Value fn = getArg(args, "$fn", Value(32.0));

    // Determine which value to use for radius
    Value radiusValue = r;
    std::string radiusPython;
    if (!d.isUndefined()) {
        radiusValue = makeDivisionValue(d, 2.0);
        radiusPython = std::to_string(d.toNumber() / 2.0);
    } else {
        radiusValue = r;
        radiusPython = std::to_string(r.toNumber());
    }

    emit("# Sphere");
    emit(nodeId + " = nodes.new('GeometryNodeMeshUVSphere')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emitSetInputOrLink(nodeId, "Radius", radiusValue, radiusPython);

    // Segments and Rings from $fn
    emitSetInputOrLink(nodeId, "Segments", fn, std::to_string(static_cast<int>(fn.toNumber())));

    // Rings = fn / 2 — build expression tree
    Value ringsValue = makeDivisionValue(fn, 2.0);
    emitSetInputOrLink(nodeId, "Rings", ringsValue, std::to_string(static_cast<int>(fn.toNumber()) / 2));

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");
}

void BlenderGenerator::emitCylinder(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value h = getArg(args, "h", getPositionalArg(args, 0, Value(1.0)));
    Value r = getArg(args, "r", Value());
    Value r1 = getArg(args, "r1", Value());
    Value r2 = getArg(args, "r2", Value());
    Value d = getArg(args, "d", Value());
    Value d1 = getArg(args, "d1", Value());
    Value d2 = getArg(args, "d2", Value());
    Value center = getArg(args, "center", Value(false));
    Value fn = getArg(args, "$fn", Value(32.0));

    // Use Cone node to support different top/bottom radii
    emit("# Cylinder (using Cone for radius support)");
    emit(nodeId + " = nodes.new('GeometryNodeMeshCone')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    // Handle height
    emitSetInputOrLink(nodeId, "Depth", h, std::to_string(h.toNumber()));

    // Determine radius values - handle expressions and computed values
    Value radiusTop, radiusBottom;
    std::string radiusTopPython, radiusBottomPython;

    // Default values
    radiusTop = Value(1.0);
    radiusBottom = Value(1.0);
    radiusTopPython = "1.0";
    radiusBottomPython = "1.0";

    // Handle various radius specifications
    if (!r.isUndefined()) {
        radiusTop = radiusBottom = r;
        radiusTopPython = radiusBottomPython = std::to_string(r.toNumber());
    }
    if (!d.isUndefined()) {
        radiusTop = radiusBottom = makeDivisionValue(d, 2.0);
        double radius = d.toNumber() / 2.0;
        radiusTopPython = radiusBottomPython = std::to_string(radius);
    }
    if (!r1.isUndefined()) {
        radiusBottom = r1;
        radiusBottomPython = std::to_string(r1.toNumber());
    }
    if (!r2.isUndefined()) {
        radiusTop = r2;
        radiusTopPython = std::to_string(r2.toNumber());
    }
    if (!d1.isUndefined()) {
        radiusBottom = makeDivisionValue(d1, 2.0);
        radiusBottomPython = std::to_string(d1.toNumber() / 2.0);
    }
    if (!d2.isUndefined()) {
        radiusTop = makeDivisionValue(d2, 2.0);
        radiusTopPython = std::to_string(d2.toNumber() / 2.0);
    }

    // Emit radius settings
    emitSetInputOrLink(nodeId, "Radius Top", radiusTop, radiusTopPython);
    emitSetInputOrLink(nodeId, "Radius Bottom", radiusBottom, radiusBottomPython);

    // Handle $fn
    emitSetInputOrLink(nodeId, "Vertices", fn, std::to_string(static_cast<int>(fn.toNumber())));

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");

    // Handle center=false
    if (!center.toBool() && !isSimpleVariableRef(center)) {
        emitBlank();
        emit("# Translate for center=false");
        std::string transId = newNodeId();
        emit(transId + " = nodes.new('GeometryNodeTransform')");
        emit(transId + ".location = (x_pos, y_pos)");

        ExprNodePtr hTree = getOrMakeLiteralTree(h);
        if (hTree && hTree->hasVariableRefs()) {
            // Build h / 2 expression tree and emit as Z component of CombineXYZ
            ExprNodePtr halfH = ExprNode::makeBinary(
                ExprNode::Op::DIVIDE, hTree, ExprNode::makeLiteral(2.0));
            emitScalarToVectorInput(transId, "Translation", halfH, 2, 0.0, 0.0, 0.0);
        } else {
            emit(transId + ".inputs['Translation'].default_value = (0, 0, " +
                 std::to_string(h.toNumber() / 2) + ")");
        }

        emit("link_nodes(links, last_geo, 'Mesh', " + transId + ", 'Geometry')");
        emit("last_geo = " + transId);
        emit("x_pos += 200");
    }
}

void BlenderGenerator::emitCircle(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value r = getArg(args, "r", getPositionalArg(args, 0, Value(1.0)));
    Value d = getArg(args, "d", Value());
    Value fn = getArg(args, "$fn", Value(32.0));

    // Determine radius value
    Value radiusValue = r;
    std::string radiusPython;
    if (!d.isUndefined()) {
        if (isSimpleVariableRef(d)) {
            radiusValue = d;
            radiusPython = d.toPython() + " / 2.0";
        } else {
            double radius = d.toNumber() / 2.0;
            radiusValue = Value(radius);
            radiusPython = std::to_string(radius);
        }
    } else {
        radiusPython = isSimpleVariableRef(r) ? r.toPython() : std::to_string(r.toNumber());
    }

    emit("# Circle (2D - using curve)");
    emit(nodeId + " = nodes.new('GeometryNodeCurvePrimitiveCircle')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emitSetInputOrLink(nodeId, "Radius", radiusValue, radiusPython);

    // Handle $fn
    if (isSimpleVariableRef(fn)) {
        std::string varName = fn.toString();
        std::string socketName = varName;
        if (varName[0] == '$') socketName = varName.substr(1);
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Resolution'])");
    } else {
        emit(nodeId + ".inputs['Resolution'].default_value = " +
             std::to_string(static_cast<int>(fn.toNumber())));
    }

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");
}

void BlenderGenerator::emitSquare(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value size = getArg(args, "size", getPositionalArg(args, 0, Value(1.0)));
    Value center = getArg(args, "center", Value(false));

    emit("# Square (2D - using curve quadrilateral)");
    emit(nodeId + " = nodes.new('GeometryNodeCurvePrimitiveQuadrilateral')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emit(nodeId + ".mode = 'RECTANGLE'");

    if (isSimpleVariableRef(size)) {
        // Link size from group_input - for scalar, link to both Width and Height
        std::string varName = size.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);
        }
        emit("# Size from variable: " + varName);
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Width'])");
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Height'])");
    } else if (size.isVector() && size.size() >= 2) {
        double width = size[0].toNumber();
        double height = size[1].toNumber();
        emit(nodeId + ".inputs['Width'].default_value = " + std::to_string(width));
        emit(nodeId + ".inputs['Height'].default_value = " + std::to_string(height));
    } else if (size.isNumber()) {
        double s = size.toNumber();
        emit(nodeId + ".inputs['Width'].default_value = " + std::to_string(s));
        emit(nodeId + ".inputs['Height'].default_value = " + std::to_string(s));
    }

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");
}

void BlenderGenerator::emitText(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value text = getArg(args, "text", getPositionalArg(args, 0, Value("Text")));
    Value size = getArg(args, "size", Value(10.0));
    Value font = getArg(args, "font", Value(""));
    Value halign = getArg(args, "halign", Value("left"));
    Value valign = getArg(args, "valign", Value("baseline"));
    Value spacing = getArg(args, "spacing", Value(1.0));

    emit("# Text (2D - using String to Curves)");
    emit(nodeId + " = nodes.new('GeometryNodeStringToCurves')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    // Set text string - handle expression (variable) or literal string
    if (isSimpleVariableRef(text)) {
        std::string varName = text.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);
        }
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['String'])");
    } else if (text.isString()) {
        emit(nodeId + ".inputs['String'].default_value = " + text.toPython());
    } else {
        // Other types - convert to string
        emit(nodeId + ".inputs['String'].default_value = str(" + text.toPython() + ")");
    }

    // Set size - handle expression
    emitSetInputOrLink(nodeId, "Size", size, std::to_string(size.toNumber()));

    // Set character spacing - handle expression
    emitSetInputOrLink(nodeId, "Character Spacing", spacing, std::to_string(spacing.toNumber()));

    // Set alignment
    std::string halignStr = halign.isString() ? halign.toString() : "left";
    std::string valignStr = valign.isString() ? valign.toString() : "baseline";

    if (halignStr == "center") {
        emit(nodeId + ".align_x = 'CENTER'");
    } else if (halignStr == "right") {
        emit(nodeId + ".align_x = 'RIGHT'");
    } else {
        emit(nodeId + ".align_x = 'LEFT'");
    }

    if (valignStr == "center") {
        emit(nodeId + ".align_y = 'MIDDLE'");
    } else if (valignStr == "top") {
        emit(nodeId + ".align_y = 'TOP'");
    } else if (valignStr == "bottom") {
        emit(nodeId + ".align_y = 'BOTTOM'");
    } else {
        emit(nodeId + ".align_y = 'BOTTOM'");  // baseline maps to bottom
    }

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");
}

void BlenderGenerator::emitPolyhedron(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value points = getArg(args, "points", getPositionalArg(args, 0, Value()));
    Value faces = getArg(args, "faces", getArg(args, "triangles", getPositionalArg(args, 1, Value())));

    emit("# Polyhedron");

    // Generate vertices as Python list using toPython() to preserve expressions
    std::string vertsCode = "[";
    if (points.isVector()) {
        for (size_t i = 0; i < points.size(); ++i) {
            const Value& pt = points[i];
            if (pt.isVector() && pt.size() >= 3) {
                if (i > 0) vertsCode += ", ";
                vertsCode += "(" + pt[0].toPython() + ", " +
                             pt[1].toPython() + ", " +
                             pt[2].toPython() + ")";
            }
        }
    }
    vertsCode += "]";

    // Generate faces as Python list
    std::string facesCode = "[";
    if (faces.isVector()) {
        for (size_t i = 0; i < faces.size(); ++i) {
            const Value& face = faces[i];
            if (face.isVector()) {
                if (i > 0) facesCode += ", ";
                facesCode += "(";
                for (size_t j = 0; j < face.size(); ++j) {
                    if (j > 0) facesCode += ", ";
                    facesCode += face[j].toPython();
                }
                facesCode += ")";
            }
        }
    }
    facesCode += "]";

    // Create mesh directly and use Mesh to Points-like approach
    // Build the mesh as a bpy.data.meshes object and set it on the main object
    emit(nodeId + "_verts = " + vertsCode);
    emit(nodeId + "_faces = " + facesCode);
    emitBlank();

    // Create the mesh data block (no scene object)
    emit("# Create polyhedron mesh data");
    emit(nodeId + "_mesh = bpy.data.meshes.new('" + nodeId + "_polyhedron')");
    emit(nodeId + "_mesh.from_pydata(" + nodeId + "_verts, [], " + nodeId + "_faces)");
    emit(nodeId + "_mesh.update()");
    emitBlank();

    // Use a Script/Mesh primitive approach: set the mesh directly as the object's mesh data
    // and skip the geometry nodes for this part, or use the mesh as a realized geometry
    emit("# Import polyhedron mesh into geometry nodes via a temporary object");
    emit(nodeId + "_obj = bpy.data.objects.new('" + nodeId + "_polyhedron', " + nodeId + "_mesh)");
    emit("bpy.context.scene.collection.objects.link(" + nodeId + "_obj)");
    emit(nodeId + "_obj.hide_viewport = True");
    emit(nodeId + "_obj.hide_render = True");
    emitBlank();

    // Use Object Info node to bring the mesh into the geometry nodes
    emit("# Reference polyhedron via Object Info node");
    emit(nodeId + " = nodes.new('GeometryNodeObjectInfo')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emit(nodeId + ".inputs['Object'].default_value = " + nodeId + "_obj");
    emit(nodeId + ".transform_space = 'RELATIVE'");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
    emit("y_pos -= 50");
}

// Transform generators
void BlenderGenerator::emitTranslate(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value v = getArg(args, "v", getPositionalArg(args, 0, Value({0.0, 0.0, 0.0})));

    emit("# Translate");
    emit(nodeId + " = nodes.new('GeometryNodeTransform')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    if (isSimpleVariableRef(v)) {
        // Link translation from group_input
        std::string varName = v.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);
        }
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Translation'])");
    } else if (v.isVector() && v.size() >= 3 && vectorHasExprTrees(v)) {
        emitVectorWithExprTrees(nodeId, "Translation", v);
    } else if (v.isVector() && v.size() >= 3) {
        emit(nodeId + ".inputs['Translation'].default_value = " + vectorToPython(v));
    }

    emit("link_nodes(links, last_geo, 'Geometry', " + nodeId + ", 'Geometry')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitRotate(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value a = getArg(args, "a", getPositionalArg(args, 0, Value(0.0)));
    Value v = getArg(args, "v", Value());

    emit("# Rotate (converting degrees to radians)");
    emit(nodeId + " = nodes.new('GeometryNodeTransform')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    if (a.isVector() && a.size() >= 3) {
        // Check if any component has variable refs
        bool hasVarRefs = false;
        ExprNodePtr compTrees[3];
        for (int i = 0; i < 3; ++i) {
            compTrees[i] = getOrMakeLiteralTree(a[i]);
            if (compTrees[i]->hasVariableRefs()) hasVarRefs = true;
        }

        if (hasVarRefs) {
            // Emit math nodes for component * PI / 180 per component
            std::string combineId = newNodeId();
            emit("# CombineXYZ for Rotation (degrees to radians via math nodes)");
            emit(combineId + " = nodes.new('ShaderNodeCombineXYZ')");
            emit(combineId + ".location = (x_pos, y_pos)");
            emit("y_pos -= 50");

            const char* components[] = {"X", "Y", "Z"};
            for (int i = 0; i < 3; ++i) {
                // Build: component * PI / 180
                ExprNodePtr radTree = ExprNode::makeBinary(
                    ExprNode::Op::MULTIPLY, compTrees[i],
                    ExprNode::makeLiteral(M_PI / 180.0));
                auto result = emitExpressionNodeTree(radTree);
                connectExprResultNamed(result, combineId, components[i]);
            }

            emit("links.new(" + combineId + ".outputs['Vector'], " + nodeId + ".inputs['Rotation'])");
        } else {
            // Euler angles - compile-time conversion
            double rx = a[0].toNumber() * M_PI / 180.0;
            double ry = a[1].toNumber() * M_PI / 180.0;
            double rz = a[2].toNumber() * M_PI / 180.0;
            emit(nodeId + ".inputs['Rotation'].default_value = (" +
                 std::to_string(rx) + ", " + std::to_string(ry) + ", " + std::to_string(rz) + ")");
        }
    } else if (a.isNumber() || a.isExpression()) {
        // Scalar angle — check for expression tree
        ExprNodePtr aTree = getOrMakeLiteralTree(a);
        if (aTree->hasVariableRefs()) {
            // Build: a * PI / 180
            ExprNodePtr radTree = ExprNode::makeBinary(
                ExprNode::Op::MULTIPLY, aTree,
                ExprNode::makeLiteral(M_PI / 180.0));
            // Emit as Z component (default rotation axis)
            emitScalarToVectorInput(nodeId, "Rotation", radTree, 2, 0.0, 0.0, 0.0);
        } else {
            double angle = a.toNumber() * M_PI / 180.0;
            if (v.isVector() && v.size() >= 3) {
                // Axis-angle rotation
                emit("# Axis-angle rotation around " + v.repr());
                emit(nodeId + ".inputs['Rotation'].default_value = (0, 0, " + std::to_string(angle) + ")");
            } else {
                // Z-axis rotation by default
                emit(nodeId + ".inputs['Rotation'].default_value = (0, 0, " + std::to_string(angle) + ")");
            }
        }
    }

    emit("link_nodes(links, last_geo, 'Geometry', " + nodeId + ", 'Geometry')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitScale(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value v = getArg(args, "v", getPositionalArg(args, 0, Value(1.0)));

    emit("# Scale");
    emit(nodeId + " = nodes.new('GeometryNodeTransform')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    if (isSimpleVariableRef(v)) {
        // Link scale from group_input
        std::string varName = v.toString();
        std::string socketName = varName;
        if (varName[0] == '$') {
            socketName = varName.substr(1);
        }
        emit("links.new(group_input.outputs['" + socketName + "'], " + nodeId + ".inputs['Scale'])");
    } else if (v.isVector() && v.size() >= 3 && vectorHasExprTrees(v)) {
        emitVectorWithExprTrees(nodeId, "Scale", v);
    } else if (v.isVector() && v.size() >= 3) {
        emit(nodeId + ".inputs['Scale'].default_value = " + vectorToPython(v));
    } else if (v.isNumber()) {
        double s = v.toNumber();
        emit(nodeId + ".inputs['Scale'].default_value = (" +
             std::to_string(s) + ", " + std::to_string(s) + ", " + std::to_string(s) + ")");
    }

    emit("link_nodes(links, last_geo, 'Geometry', " + nodeId + ", 'Geometry')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitMirror(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value v = getArg(args, "v", getPositionalArg(args, 0, Value({1.0, 0.0, 0.0})));

    emit("# Mirror (using scale with negative values)");
    emit(nodeId + " = nodes.new('GeometryNodeTransform')");
    emit(nodeId + ".location = (x_pos, y_pos)");

    if (v.isVector() && v.size() >= 3) {
        double sx = v[0].toNumber() != 0 ? -1.0 : 1.0;
        double sy = v[1].toNumber() != 0 ? -1.0 : 1.0;
        double sz = v[2].toNumber() != 0 ? -1.0 : 1.0;
        emit(nodeId + ".inputs['Scale'].default_value = (" +
             std::to_string(sx) + ", " + std::to_string(sy) + ", " + std::to_string(sz) + ")");
    }

    emit("link_nodes(links, last_geo, 'Geometry', " + nodeId + ", 'Geometry')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitOffset(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value r = getArg(args, "r", getPositionalArg(args, 0, Value()));
    Value delta = getArg(args, "delta", Value());

    // Determine offset value and whether to round corners
    bool useRounding = !r.isUndefined();
    Value offsetVal;
    if (!r.isUndefined()) {
        offsetVal = r;
    } else if (!delta.isUndefined()) {
        offsetVal = delta;
    } else {
        // Positional arg or default
        offsetVal = getPositionalArg(args, 0, Value(1.0));
    }

    // Use toPython() for the Python value string — this preserves variable references
    // (e.g., "wall / 2") that are valid Python inside module functions.
    std::string offsetPython = offsetVal.isExpression() ?
        offsetVal.toPython() : std::to_string(offsetVal.toNumber());

    // Try to determine the numeric value for fillet decisions.
    // This may return 0 for unresolvable module parameters, so we check
    // whether the expression tree has only resolvable variables.
    ExprNodePtr offsetTree = resolveExprTree(offsetVal);
    bool canEvaluate = !offsetTree || !offsetTree->hasVariableRefs() ||
                       exprTreeHasOnlyGroupInputVars(offsetTree);
    double offsetNum = 0.0;
    if (!canEvaluate) {
        // Can't determine sign at compile time (e.g., module parameter).
        // Skip fillet since we don't know if offset is positive.
        offsetNum = 0.0;
    } else {
        offsetNum = offsetVal.isExpression() ? evaluateExpr(offsetVal) : offsetVal.toNumber();
    }

    emit("# Offset");

    // Step 1: Fillet corners (only for r mode with positive offset)
    if (useRounding && offsetNum > 0) {
        std::string filletId = newNodeId();
        emit(filletId + " = nodes.new('GeometryNodeFilletCurve')");
        emit(filletId + ".location = (x_pos, y_pos)");
        emitSetInputOrLink(filletId, "Radius", offsetVal, offsetPython);
        emit(filletId + ".inputs['Count'].default_value = 8");
        emit("link_nodes(links, last_geo, 'Curve', " + filletId + ", 'Curve')");
        emit("last_geo = " + filletId);
        emit("x_pos += 200");
    }

    // Step 2: Offset each point along its normal
    std::string normalId = newNodeId();
    emit(normalId + " = nodes.new('GeometryNodeInputNormal')");
    emit(normalId + ".location = (x_pos, y_pos)");

    std::string scaleId = newNodeId();
    emit(scaleId + " = nodes.new('ShaderNodeVectorMath')");
    emit(scaleId + ".operation = 'SCALE'");
    emit(scaleId + ".location = (x_pos, y_pos)");
    emit("links.new(" + normalId + ".outputs['Normal'], " + scaleId + ".inputs[0])");
    emitSetInputOrLink(scaleId, "Scale", offsetVal, offsetPython);

    std::string setposId = newNodeId();
    emit(setposId + " = nodes.new('GeometryNodeSetPosition')");
    emit(setposId + ".location = (x_pos, y_pos)");
    emit("link_nodes(links, last_geo, 'Geometry', " + setposId + ", 'Geometry')");
    emit("links.new(" + scaleId + ".outputs['Vector'], " + setposId + ".inputs['Offset'])");
    emit("last_geo = " + setposId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitHull(const Arguments& args) {
    std::string nodeId = newNodeId();

    emit("# Hull (convex hull)");
    emit(nodeId + " = nodes.new('GeometryNodeConvexHull')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emit("link_nodes(links, last_geo, 'Geometry', " + nodeId + ", 'Geometry')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::emitMinkowski(const Arguments& args) {
    // Minkowski sum is not directly available in Blender geometry nodes
    // We'll just pass through the geometry with a comment
    emit("# Minkowski sum (not directly supported - passing geometry through)");
    emit("# To implement Minkowski, you would need custom node setup or scripting");
}

// Boolean operation
void BlenderGenerator::emitBooleanOp(BooleanNode& node) {
    if (node.children().empty()) {
        return;
    }

    std::string opName;
    std::string blenderOp;

    switch (node.type()) {
        case ASTNode::Type::Union:
            opName = "Union";
            blenderOp = "UNION";
            break;
        case ASTNode::Type::Difference:
            opName = "Difference";
            blenderOp = "DIFFERENCE";
            break;
        case ASTNode::Type::Intersection:
            opName = "Intersection";
            blenderOp = "INTERSECT";
            break;
        default:
            return;
    }

    // Collect all actual children (unpacking container unions)
    // Separate assignments and module definitions from geometry-producing nodes
    std::vector<ASTNodePtr> actualChildren;
    std::vector<ASTNodePtr> assignments;
    std::vector<ASTNodePtr> moduleDefinitions;

    for (auto& child : node.children()) {
        // Check if this is a container Union (marked with debug flag)
        if (child->type() == ASTNode::Type::Union && child->isDebug()) {
            // Unpack the container's children
            for (auto& grandchild : child->children()) {
                if (grandchild->type() == ASTNode::Type::Assignment) {
                    assignments.push_back(grandchild);
                } else if (grandchild->type() == ASTNode::Type::Module) {
                    // Nested module definition - doesn't produce geometry
                    moduleDefinitions.push_back(grandchild);
                } else {
                    actualChildren.push_back(grandchild);
                }
            }
        } else if (child->type() == ASTNode::Type::Assignment) {
            assignments.push_back(child);
        } else if (child->type() == ASTNode::Type::Module) {
            // Nested module definition - doesn't produce geometry
            moduleDefinitions.push_back(child);
        } else {
            actualChildren.push_back(child);
        }
    }

    // Process assignments first (they define variables)
    for (auto& assign : assignments) {
        assign->accept(*this);
    }

    // Process nested module definitions (register them but don't generate geometry)
    for (auto& mod : moduleDefinitions) {
        // Just skip nested modules for now - they're not supported yet
        // In a full implementation, we would register them in a local scope
    }

    // Only emit boolean op comment if we have geometry children
    if (actualChildren.empty()) {
        return;
    }

    // If only one child, just process it without boolean operation
    if (actualChildren.size() == 1) {
        actualChildren[0]->accept(*this);
        return;
    }

    // Use a unique counter for this boolean scope to avoid variable name collisions
    int boolScopeId = node_counter_++;

    emit("# " + opName);

    // Helper: ensure geometry is mesh (fill curves for 2D boolean operands)
    // Nodes like SetPosition, FilletCurve, CurvePrimitiveCircle, etc. may output
    // curve geometry that needs to be filled before mesh boolean operations.
    // We check the node type to decide if filling is needed.
    std::string fillHelper = "ensure_mesh_" + std::to_string(boolScopeId);
    emit("def " + fillHelper + "(geo_node):");
    indent_++;
    emit("\"\"\"Fill curve geometry for boolean input\"\"\"");
    emit("nonlocal x_pos, y_pos");
    emit("curve_types = {'GeometryNodeCurvePrimitiveCircle', 'GeometryNodeCurvePrimitiveQuadrilateral',");
    emit("               'GeometryNodeCurvePrimitiveLine', 'GeometryNodeCurvePrimitiveStar',");
    emit("               'GeometryNodeFilletCurve', 'GeometryNodeSetPosition',");
    emit("               'GeometryNodeStringToCurves', 'GeometryNodeCurveToPoints',");
    emit("               'GeometryNodeCurvePrimitiveArc', 'GeometryNodeCurvePrimitiveBezierSegment'}");
    emit("if geo_node is not None and geo_node.bl_idname in curve_types:");
    indent_++;
    emit("fill = nodes.new('GeometryNodeFillCurve')");
    emit("fill.location = (x_pos, y_pos)");
    emit("link_nodes(links, geo_node, 'Curve', fill, 'Curve')");
    emit("x_pos += 200");
    emit("return fill");
    indent_--;
    emit("return geo_node");
    indent_--;

    // Process first child
    std::string firstGeo = "bool_first_" + std::to_string(boolScopeId);
    emit(firstGeo + " = None");

    actualChildren[0]->accept(*this);
    emit("last_geo = " + fillHelper + "(last_geo)");
    emit(firstGeo + " = last_geo");

    // Process remaining children and combine
    for (size_t i = 1; i < actualChildren.size(); ++i) {
        actualChildren[i]->accept(*this);

        emit("last_geo = " + fillHelper + "(last_geo)");

        std::string boolId = newNodeId();
        emit(boolId + " = nodes.new('GeometryNodeMeshBoolean')");
        emit(boolId + ".location = (x_pos, y_pos)");
        emit(boolId + ".operation = '" + blenderOp + "'");

        // Blender 5.x boolean: inputs[0] = 'Mesh 1' (single), inputs[1] = 'Mesh' (multi-input)
        // DIFFERENCE: first operand -> inputs[0], rest -> inputs[1]
        // INTERSECT/UNION: all operands -> inputs[1] (multi-input)
        if (blenderOp == "DIFFERENCE") {
            emit("links.new(" + firstGeo + ".outputs[0], " + boolId + ".inputs[0])");
            emit("links.new(last_geo.outputs[0], " + boolId + ".inputs[1])");
        } else {
            // INTERSECT and UNION: both go to multi-input Mesh (index 1)
            emit("links.new(" + firstGeo + ".outputs[0], " + boolId + ".inputs[1])");
            emit("links.new(last_geo.outputs[0], " + boolId + ".inputs[1])");
        }
        emit(firstGeo + " = " + boolId);
        emit("x_pos += 200");
        emit("y_pos -= 50");
    }

    emit("last_geo = " + firstGeo);
}

// Extrude generators
void BlenderGenerator::emitLinearExtrude(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value height = getArg(args, "height", getPositionalArg(args, 0, Value(1.0)));
    Value twist = getArg(args, "twist", Value(0.0));
    Value scale_val = getArg(args, "scale", Value(1.0));
    Value center = getArg(args, "center", Value(false));

    emit("# Linear Extrude");

    // First fill the curve
    std::string fillId = newNodeId();
    emit(fillId + " = nodes.new('GeometryNodeFillCurve')");
    emit(fillId + ".location = (x_pos, y_pos)");
    emit("link_nodes(links, last_geo, 'Curve', " + fillId + ", 'Curve')");
    emit("x_pos += 200");

    // Extrude with Individual=False for proper solid extrusion
    emit(nodeId + " = nodes.new('GeometryNodeExtrudeMesh')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emit(nodeId + ".inputs['Individual'].default_value = False");

    // Set offset direction (0,0,1) and use Offset Scale for height
    emit(nodeId + ".inputs['Offset'].default_value = (0, 0, 1)");
    ExprNodePtr heightTree = getOrMakeLiteralTree(height);
    if (heightTree->hasVariableRefs()) {
        auto result = emitExpressionNodeTree(heightTree);
        connectExprResultNamed(result, nodeId, "Offset Scale");
    } else {
        emit(nodeId + ".inputs['Offset Scale'].default_value = " +
             std::to_string(height.toNumber()));
    }
    emit("link_nodes(links, " + fillId + ", 'Mesh', " + nodeId + ", 'Mesh')");
    emit("last_geo = " + nodeId);
    emit("x_pos += 200");

    // Handle scale parameter — scale the top face
    double scaleNum = scale_val.isExpression() ? evaluateExpr(scale_val) : scale_val.toNumber();
    if (scaleNum != 1.0) {
        std::string scaleId = newNodeId();
        emit("# Scale top face for linear_extrude(scale=" + std::to_string(scaleNum) + ")");
        emit(scaleId + " = nodes.new('GeometryNodeScaleElements')");
        emit(scaleId + ".location = (x_pos, y_pos)");
        emit(scaleId + ".inputs['Scale'].default_value = " + std::to_string(scaleNum));
        emit("links.new(" + nodeId + ".outputs['Mesh'], " + scaleId + ".inputs['Geometry'])");
        emit("links.new(" + nodeId + ".outputs['Top'], " + scaleId + ".inputs['Selection'])");
        emit("last_geo = " + scaleId);
        emit("x_pos += 200");
    }
}

void BlenderGenerator::emitRotateExtrude(const Arguments& args) {
    std::string nodeId = newNodeId();

    Value angle = getArg(args, "angle", Value(360.0));
    Value fn = getArg(args, "$fn", Value(32.0));

    emit("# Rotate Extrude (Lathe/Revolution)");
    emit("# Note: Blender doesn't have direct equivalent - using curve to mesh");

    // Use curve to mesh with profile
    emit(nodeId + " = nodes.new('GeometryNodeCurveToMesh')");
    emit(nodeId + ".location = (x_pos, y_pos)");
    emit("link_nodes(links, last_geo, 'Curve', " + nodeId + ", 'Curve')");

    emit("last_geo = " + nodeId);
    emit("x_pos += 200");
}

void BlenderGenerator::processChildren(ASTNode& node) {
    for (auto& child : node.children()) {
        if (!child->isDisabled() && !child->isBackground()) {
            child->accept(*this);
        }
    }
}

std::string BlenderGenerator::vectorToPython(const Value& v) {
    if (v.isVector()) {
        std::ostringstream ss;
        ss << "(";
        for (size_t i = 0; i < v.size(); ++i) {
            if (i > 0) ss << ", ";
            ss << v[i].toPython();
        }
        ss << ")";
        return ss.str();
    }
    return v.toPython();
}

bool BlenderGenerator::vectorHasExpressions(const Value& v) {
    if (!v.isVector()) return false;
    for (size_t i = 0; i < v.size(); ++i) {
        if (v[i].isExpression()) return true;
    }
    return false;
}

bool BlenderGenerator::vectorHasExprTrees(const Value& v) {
    if (!v.isVector()) return false;
    for (size_t i = 0; i < v.size(); ++i) {
        if (v[i].exprTree() && v[i].exprTree()->hasVariableRefs()) return true;
    }
    return false;
}

ExprNodePtr BlenderGenerator::resolveExprTree(const Value& value) {
    ExprNodePtr tree = value.exprTree();
    if (!tree) return nullptr;

    // If it's a VarRef for a non-group-input variable, expand it
    if (tree->kind == ExprNode::Kind::VarRef &&
        group_input_vars_.find(tree->var_name) == group_input_vars_.end()) {
        // Look up in variables_ map
        auto it = variables_.find(tree->var_name);
        if (it != variables_.end()) {
            return resolveExprTree(it->second);
        }
        return tree;
    }
    // For binary/unary ops, recursively resolve children
    if (tree->kind == ExprNode::Kind::BinaryOp) {
        auto resolved = std::make_shared<ExprNode>();
        resolved->kind = ExprNode::Kind::BinaryOp;
        resolved->op = tree->op;
        // Create temp Values to recurse on left/right
        Value leftVal;
        leftVal.setExprTree(tree->left);
        Value rightVal;
        rightVal.setExprTree(tree->right);
        resolved->left = resolveExprTree(leftVal);
        resolved->right = resolveExprTree(rightVal);
        return resolved;
    }
    if (tree->kind == ExprNode::Kind::UnaryOp) {
        auto resolved = std::make_shared<ExprNode>();
        resolved->kind = ExprNode::Kind::UnaryOp;
        resolved->op = tree->op;
        Value operandVal;
        operandVal.setExprTree(tree->left);
        resolved->left = resolveExprTree(operandVal);
        return resolved;
    }
    return tree;  // Literal or group_input VarRef
}

EmitResult BlenderGenerator::emitExpressionNodeTree(const ExprNodePtr& expr) {
    if (!expr) return {"__literal__", "Value", 0.0, false};

    switch (expr->kind) {
        case ExprNode::Kind::Literal:
            return {"__literal__", "Value", expr->literal_value, false};

        case ExprNode::Kind::VarRef: {
            // Should be a group_input variable at this point (after resolution)
            std::string socketName = expr->var_name;
            if (!socketName.empty() && socketName[0] == '$') {
                socketName = socketName.substr(1);
            }
            return {"group_input", socketName, 0.0, true};
        }

        case ExprNode::Kind::UnaryOp: {
            // NEGATE: emit MULTIPLY by -1
            auto operandResult = emitExpressionNodeTree(expr->left);
            std::string mathId = newNodeId();
            emit("# Negate");
            emit(mathId + " = nodes.new('ShaderNodeMath')");
            emit(mathId + ".operation = 'MULTIPLY'");
            emit(mathId + ".location = (x_pos, y_pos)");
            emit("y_pos -= 50");
            connectExprResult(operandResult, mathId, 0);
            emit(mathId + ".inputs[1].default_value = -1.0");
            return {mathId, "Value", 0.0, false};
        }

        case ExprNode::Kind::BinaryOp: {
            auto leftResult = emitExpressionNodeTree(expr->left);
            auto rightResult = emitExpressionNodeTree(expr->right);

            std::string opStr;
            switch (expr->op) {
                case ExprNode::Op::ADD: opStr = "ADD"; break;
                case ExprNode::Op::SUBTRACT: opStr = "SUBTRACT"; break;
                case ExprNode::Op::MULTIPLY: opStr = "MULTIPLY"; break;
                case ExprNode::Op::DIVIDE: opStr = "DIVIDE"; break;
                case ExprNode::Op::MODULO: opStr = "MODULO"; break;
                case ExprNode::Op::POWER: opStr = "POWER"; break;
                default: opStr = "ADD"; break;
            }

            std::string mathId = newNodeId();
            emit(mathId + " = nodes.new('ShaderNodeMath')");
            emit(mathId + ".operation = '" + opStr + "'");
            emit(mathId + ".location = (x_pos, y_pos)");
            emit("y_pos -= 50");
            connectExprResult(leftResult, mathId, 0);
            connectExprResult(rightResult, mathId, 1);
            return {mathId, "Value", 0.0, false};
        }
    }
    return {"__literal__", "Value", 0.0, false};
}

void BlenderGenerator::connectExprResult(const EmitResult& result, const std::string& targetNode, int inputIndex) {
    if (result.nodeId == "__literal__") {
        emit(targetNode + ".inputs[" + std::to_string(inputIndex) + "].default_value = " +
             std::to_string(result.literalValue));
    } else if (result.isGroupInput) {
        emit("links.new(group_input.outputs['" + result.socketName + "'], " +
             targetNode + ".inputs[" + std::to_string(inputIndex) + "])");
    } else {
        emit("links.new(" + result.nodeId + ".outputs['" + result.socketName + "'], " +
             targetNode + ".inputs[" + std::to_string(inputIndex) + "])");
    }
}

void BlenderGenerator::connectExprResultNamed(const EmitResult& result, const std::string& targetNode, const std::string& inputName) {
    if (result.nodeId == "__literal__") {
        emit(targetNode + ".inputs['" + inputName + "'].default_value = " +
             std::to_string(result.literalValue));
    } else if (result.isGroupInput) {
        emit("links.new(group_input.outputs['" + result.socketName + "'], " +
             targetNode + ".inputs['" + inputName + "'])");
    } else {
        emit("links.new(" + result.nodeId + ".outputs['" + result.socketName + "'], " +
             targetNode + ".inputs['" + inputName + "'])");
    }
}

std::string BlenderGenerator::emitVectorWithExprTrees(const std::string& targetNodeId,
                                                       const std::string& inputName,
                                                       const Value& vec) {
    std::string combineId = newNodeId();
    emit("# CombineXYZ for " + inputName);
    emit(combineId + " = nodes.new('ShaderNodeCombineXYZ')");
    emit(combineId + ".location = (x_pos, y_pos)");
    emit("y_pos -= 50");

    const char* components[] = {"X", "Y", "Z"};
    for (size_t i = 0; i < 3 && i < vec.size(); ++i) {
        const Value& comp = vec[i];
        ExprNodePtr tree = resolveExprTree(comp);
        if (tree && tree->hasVariableRefs()) {
            auto result = emitExpressionNodeTree(tree);
            connectExprResultNamed(result, combineId, components[i]);
        } else if (comp.exprTree() && comp.exprTree()->kind == ExprNode::Kind::Literal) {
            emit(combineId + ".inputs['" + components[i] + "'].default_value = " +
                 std::to_string(comp.exprTree()->literal_value));
        } else if (comp.isNumber()) {
            emit(combineId + ".inputs['" + components[i] + "'].default_value = " +
                 std::to_string(comp.toNumber()));
        } else if (tree) {
            // Literal tree from resolved computation
            auto result = emitExpressionNodeTree(tree);
            connectExprResultNamed(result, combineId, components[i]);
        } else {
            emit(combineId + ".inputs['" + components[i] + "'].default_value = " + comp.toPython());
        }
    }

    emit("links.new(" + combineId + ".outputs['Vector'], " + targetNodeId + ".inputs['" + inputName + "'])");
    return combineId;
}

double BlenderGenerator::evaluateExpr(const Value& value) {
    ExprNodePtr tree = value.exprTree();
    if (tree) return evaluateExprTree(tree);
    return value.toNumber();
}

double BlenderGenerator::evaluateExprTree(const ExprNodePtr& tree) {
    if (!tree) return 0.0;
    switch (tree->kind) {
        case ExprNode::Kind::Literal:
            return tree->literal_value;
        case ExprNode::Kind::VarRef: {
            auto it = variables_.find(tree->var_name);
            if (it != variables_.end()) {
                return evaluateExpr(it->second);
            }
            return 0.0;
        }
        case ExprNode::Kind::UnaryOp: {
            double operand = evaluateExprTree(tree->left);
            if (tree->op == ExprNode::Op::NEGATE) return -operand;
            return operand;
        }
        case ExprNode::Kind::BinaryOp: {
            double left = evaluateExprTree(tree->left);
            double right = evaluateExprTree(tree->right);
            switch (tree->op) {
                case ExprNode::Op::ADD: return left + right;
                case ExprNode::Op::SUBTRACT: return left - right;
                case ExprNode::Op::MULTIPLY: return left * right;
                case ExprNode::Op::DIVIDE: return right != 0 ? left / right : 0.0;
                case ExprNode::Op::MODULO: return right != 0 ? std::fmod(left, right) : 0.0;
                case ExprNode::Op::POWER: return std::pow(left, right);
                default: return 0.0;
            }
        }
    }
    return 0.0;
}

ExprNodePtr BlenderGenerator::getOrMakeLiteralTree(const Value& value) {
    ExprNodePtr tree = resolveExprTree(value);
    if (tree) return tree;
    // No expression tree — create a literal from the numeric value
    return ExprNode::makeLiteral(value.toNumber());
}

Value BlenderGenerator::makeDivisionValue(const Value& numerator, double divisor) {
    ExprNodePtr numTree = getOrMakeLiteralTree(numerator);
    ExprNodePtr divTree = ExprNode::makeBinary(
        ExprNode::Op::DIVIDE, numTree, ExprNode::makeLiteral(divisor));
    Value result;
    result.setExprTree(divTree);
    return result;
}

void BlenderGenerator::emitScalarToVectorInput(const std::string& targetNodeId,
                                                const std::string& inputName,
                                                const ExprNodePtr& tree,
                                                int component,
                                                double defaultX, double defaultY, double defaultZ) {
    std::string combineId = newNodeId();
    emit("# CombineXYZ for " + inputName);
    emit(combineId + " = nodes.new('ShaderNodeCombineXYZ')");
    emit(combineId + ".location = (x_pos, y_pos)");
    emit("y_pos -= 50");

    double defaults[] = {defaultX, defaultY, defaultZ};
    const char* components[] = {"X", "Y", "Z"};

    for (int i = 0; i < 3; ++i) {
        if (i == component) {
            auto result = emitExpressionNodeTree(tree);
            connectExprResultNamed(result, combineId, components[i]);
        } else {
            emit(combineId + ".inputs['" + std::string(components[i]) + "'].default_value = " +
                 std::to_string(defaults[i]));
        }
    }

    emit("links.new(" + combineId + ".outputs['Vector'], " + targetNodeId + ".inputs['" + inputName + "'])");
}

void BlenderGenerator::emitScalarToAllVectorComponents(const std::string& targetNodeId,
                                                        const std::string& inputName,
                                                        const ExprNodePtr& tree) {
    // Emit the expression once, then wire it to all three components of a CombineXYZ
    auto result = emitExpressionNodeTree(tree);

    std::string combineId = newNodeId();
    emit("# CombineXYZ (scalar to all components) for " + inputName);
    emit(combineId + " = nodes.new('ShaderNodeCombineXYZ')");
    emit(combineId + ".location = (x_pos, y_pos)");
    emit("y_pos -= 50");

    const char* components[] = {"X", "Y", "Z"};
    for (int i = 0; i < 3; ++i) {
        connectExprResultNamed(result, combineId, components[i]);
    }

    emit("links.new(" + combineId + ".outputs['Vector'], " + targetNodeId + ".inputs['" + inputName + "'])");
}

void BlenderGenerator::collectGroupInputVars(ASTNode& node) {
    for (auto& child : node.children()) {
        if (child->type() == ASTNode::Type::Assignment) {
            auto* assign = dynamic_cast<AssignmentNode*>(child.get());
            if (assign) {
                // Only promote to group_input if this is a top-level variable.
                // Module-internal variables (like length, cutoff_size) should NOT
                // become group_input sockets.
                if (top_level_vars_.find(assign->name()) == top_level_vars_.end()) {
                    // Skip module-internal variables
                } else {
                    const Value& val = assign->value();
                    if (val.isNumber() || val.isBool() || val.isString()) {
                        group_input_vars_.insert(assign->name());
                    } else if (val.isVector() && val.size() == 3) {
                        bool allConcrete = true;
                        for (size_t i = 0; i < val.size(); ++i) {
                            if (val[i].isExpression()) { allConcrete = false; break; }
                        }
                        if (allConcrete) {
                            group_input_vars_.insert(assign->name());
                        }
                    }
                }
            }
        }
        // Recurse into children (container unions, etc.)
        collectGroupInputVars(*child);
    }
}

bool BlenderGenerator::moduleUsesChildren(ASTNode& node) {

    // Check if any descendant is a ChildrenNode
    for (auto& child : node.children()) {
        if (child->type() == ASTNode::Type::Children) {
            return true;
        }
        if (moduleUsesChildren(*child)) {
            return true;
        }
    }
    return false;
}

} // namespace scad2blender
